// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6sL7SchqJBfAvw2i2W85HkdPD0LnMYPE',
    appId: '1:842182289361:web:9caa1af22ebbcfdbd422f0',
    messagingSenderId: '842182289361',
    projectId: 'flutter-project-mynotes-gjb',
    authDomain: 'flutter-project-mynotes-gjb.firebaseapp.com',
    storageBucket: 'flutter-project-mynotes-gjb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh6piNvNM38a3yiixZ-_UtkYi1D6C31Yc',
    appId: '1:842182289361:android:0390bc7740b129f0d422f0',
    messagingSenderId: '842182289361',
    projectId: 'flutter-project-mynotes-gjb',
    storageBucket: 'flutter-project-mynotes-gjb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxPj_D_VatfkE6Dk-hvszr4OHooyQ2zg',
    appId: '1:842182289361:ios:e15fbd4b75cec5add422f0',
    messagingSenderId: '842182289361',
    projectId: 'flutter-project-mynotes-gjb',
    storageBucket: 'flutter-project-mynotes-gjb.appspot.com',
    iosBundleId: 'com.newapp.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFxPj_D_VatfkE6Dk-hvszr4OHooyQ2zg',
    appId: '1:842182289361:ios:4db3e06895fe8eb2d422f0',
    messagingSenderId: '842182289361',
    projectId: 'flutter-project-mynotes-gjb',
    storageBucket: 'flutter-project-mynotes-gjb.appspot.com',
    iosBundleId: 'com.newapp.mynotes.RunnerTests',
  );
}
